kube-prometheus-stack:
  defaultRules:
    create: false
  alertmanager:
    enabled: false
  grafana:
    enabled: false
  kubeEtcd:
    enabled: false
  nodeExporter:
    enabled: false
  prometheus:
    enabled: false
    prometheusSpec: 
      externalLabels:
        cluster: homelab-k3s
      retention: 3d
      retentionSize: "5GiB"
      remoteWrite:
        - url: http://mimir-gateway.mimir.svc.cluster.local/api/v1/push
      writeRelabelConfigs:
        - sourceLabels: [__name__]
          regex: 'apiserver_request_duration_seconds_bucket|apiserver_request_body_size_bucket|apiserver_response_sizes_bucket'
          action: drop
