mimir-distributed:
  global:
    extraEnv: []
  ingester:
    replicas: 0
    zoneAwareReplication:
      enabled: false
  ruler_querier:
    replicas: 0
  ruler_query_scheduler:
    replicas: 0
  querier:
    replicas: 0
  query_scheduler:
    replicas: 0
  store_gateway:
    replicas: 0
    zoneAwareReplication:
      enabled: false

  runtimeConfig:
    overrides:
      anonymous:
        max_global_series_per_user: 450000