apiVersion: v2
name: pyroscope-wrapper
description: Wrapper chart to install pyroscope via Helm
type: application
version: 0.1.0

dependencies:
  - name: pyroscope
    version: "1.19.2"
    repository: https://grafana.github.io/helm-charts
